services:

  pcdex-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pcdex-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "PcdexPassword2026!"
    ports:
      - "1433:1433"
    volumes:
      - pcdex-sql-data:/var/opt/mssql
    networks:
      - pcdex-network

  backend:
    build: ./backend
    container_name: pcdex-backend
    ports:
      - "3000:3000"
    depends_on:
      - pcdex-db
    networks:
      - pcdex-network

  frontend:
    build: ./frontend
    container_name: pcdex-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - pcdex-network

volumes:
  pcdex-sql-data:

networks:
  pcdex-network: